config/routes.rb
Rails.application.routes.draw do

# verb 'path', to: 'controller#action'
# read all the restaurants
get 'tasks', to: 'tasks#index'

# create a restaurant
get 'tasks/new', to: 'tasks#new'
post 'tasks', to: 'tasks#create'

# read one restaurant
get 'tasks/:id', to: 'tasks#show', as: :task

# update a restaurant
get 'tasks/:id/edit', to: 'tasks#edit', as: :taskk
patch 'tasks/:id', to: 'tasks#update'

# delete a restaurant
delete 'tasks/:id', to: 'tasks#destroy', as: :d_task

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

   private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
  <% link_to "back to home", tasks_path %>
<% end %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>

<% @tasks.each do |t|  %>
  <% if t.completed == true %>
    <p> [X] <%=link_to "#{t.title}", task_path(t.id)%>  </p>
  <% else %>
    <p> "[ ] <%= link_to "#{t.title}", task_path(t.id)%> </p>
  <% end %>
<% end %>

<h2><%= link_to "Add a new Task", tasks_new_path %></h2>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
  <% link_to "back to home", tasks_path %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p> "TITLE: <%= @task.title %>, DETAILS: <%= @task.details %>, DONE? <%= @task.completed %> " </p>

<%=link_to 'edit this task', taskk_path(@task.id) %>

<%=link_to 'back to home', tasks_path %>

<%= link_to "Delete Task", d_task_path(@task), method: :delete, data: { confirm: 'Are you sure?' } %>